### ISSUE TITLE
LDAP nil pointer dereference

### ISSUE THREAD

**Issue by mcallaway** [cesanta/docker_auth#88]
Does ldaps work?

I get the following using port 636 or 389 with tls true or false.

    ldap_auth:
      addr: "ipa1.my.domain.com:636"
      tls: false
      bind_dn: uid=proxyuser,cn=users,cn=accounts,dc=gsc,dc=wustl,dc=edu
      bind_password_file: /config/binddn_password
      base: "cn=users,cn=accounts,dc=gsc,dc=wustl,dc=edu"
      filter: "(&(uid=${account})(objectClass=posixAccount))"

    docker_auth_1 | I0404 13:49:14.051738       1 server.go:312] Auth request: {proxyuser:***@10.0.7.101:62793 []}
    docker_auth_1 | I0404 13:49:14.051789       1 server.go:168] Authn static proxyuser -> false, did not match any rule
    docker_auth_1 | I0404 13:49:14.051862       1 ldap_auth.go:100] Bind read-only user (DN = uid=proxyuser,cn=users,cn=accounts,dc=my,dc=domain,dc=com)
    docker_auth_1 | I0404 13:49:14.051984       1 server.go:1934] http: panic serving 10.0.7.101:62793: runtime error: invalid memory address or nil pointer dereference
    docker_auth_1 | goroutine 49 [running]:
    docker_auth_1 | net/http.(*conn).serve.func1(0xc82031abb0, 0x7f5dd00d4088, 0xc8204c4000)
    docker_auth_1 |         /usr/local/go/src/net/http/server.go:1287 +0xb5
    docker_auth_1 | github.com/go-ldap/ldap.(*Conn).Close(0x0)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/Godeps/_workspace/src/github.com/go-ldap/ldap/conn.go:132 +0x6d
    docker_auth_1 | github.com/go-ldap/ldap.(*Conn).Bind(0x0, 0xc8201356c0, 0x39, 0xc8204c6590, 0x6, 0x0, 0x0)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/Godeps/_workspace/src/github.com/go-ldap/ldap/bind.go:94 +0x3c
    docker_auth_1 | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).bindReadOnlyUser(0xc820138080, 0x0, 0x0, 0x0)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:101 +0x266
    docker_auth_1 | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).Authenticate(0xc820138080, 0xc820557452, 0x9, 0xc8204c648a, 0x6, 0x0, 0x0, 0x0)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:67 +0x11d
    docker_auth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).Authenticate(0xc8204830c0, 0xc820568100, 0x11, 0x0, 0x0)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:167 +0x11e
    docker_auth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).doAuth(0xc8204830c0, 0x7f5dd00944e0, 0xc82055e630, 0xc820515880)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:314 +0x3b3
    docker_auth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).ServeHTTP(0xc8204830c0, 0x7f5dd00944e0, 0xc82055e630, 0xc820515880)
    docker_auth_1 |         /go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:286 +0x1ef
    docker_auth_1 | net/http.serverHandler.ServeHTTP(0xc8204adf20, 0x7f5dd00944e0, 0xc82055e630, 0xc820515880)
    docker_auth_1 |         /usr/local/go/src/net/http/server.go:1862 +0x19e
    docker_auth_1 | net/http.(*conn).serve(0xc82031abb0)
    docker_auth_1 |         /usr/local/go/src/net/http/server.go:1361 +0xbee
    docker_auth_1 | created by net/http.(*Server).Serve
    docker_auth_1 |         /usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by mcallaway** [comment]
Duplicate of #73 sorry.

**Comment by mcallaway** [comment]
See #73 and #89
